[metadata]
name = "beer_fire_detection"
version = 0.0.0

[options]
packages = find:
install_requires =
    rclpy
    sensor_msgs
    std_msgs
    numpy

[options.entry_points]
console_scripts =
    fire_detector = beer_fire_detection.fire_detector:main
    synthetic_thermal_demo = beer_fire_detection.synthetic_thermal_demo:main
